### ISSUE TITLE
Maintainance plan

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/vscode-wasm#17]
Hi @reklatsmasters, first of all... great work on the extension!

I'm Syrus, CEO of [Wasmer](https://wasmer.io).
The vscode extension is a bit unmaintained and I was wondering if you would be open for Wasmer to maintain it. We have a lot of ideas on how to improve the extension and would be great if we can action them and move its development forward!

Let me know :)

**Comment by reklatsmasters** [comment]
Hi Syrus,

In this year i'm busy on full time job, and Open Source is not my hobby anymore. Anyway, i'm ready for give Wasmer an access (or ownership). And i'm glad to see a support for existing audience instead of creating a fork.

Send me list of a things should i do.

**Comment by syrusakbary** [comment]
Awesome. If you can give us owner rights that would be great.

We would need it in the repo (to add new features, add more maintainers, publish releases, ...) and in the extension (to be able to publish new versions).

I've spent some time on making screenshots to make it easier!

## Github - Repo permissions

Go to the Github Repo settings: https://github.com/wasmerio/wasmer/settings
1. Click Collaborators and Teams
2. Go to collaborators section, type `syrusakbary`
3. Click Add collaborator
4. Add admin permissions to the user

<img width="1265" alt="Screen Shot 2019-09-01 at 12 03 25 PM" src="https://user-images.githubusercontent.com/188257/64081065-c13fb900-ccb0-11e9-8581-ea5bd40b81c8.png">
<img width="752" alt="Screen Shot 2019-09-01 at 12 08 19 PM" src="https://user-images.githubusercontent.com/188257/64081105-49be5980-ccb1-11e9-9059-b96bf5b536b3.png">


## VisualStudio Marketplace - Extension permissions

You can go to this page: https://marketplace.visualstudio.com/manage
1. Click Members
2. Click `+ Add`
3. Add `me@syrusakbary.com` as Owner (I tried to use `syrus@wasmer.io` but the UI complains saying that is an invalid email :( )

<img width="1244" alt="Screen Shot 2019-09-01 at 11 51 48 AM" src="https://user-images.githubusercontent.com/188257/64081029-378feb80-ccb0-11e9-812f-5a1eab774e5d.png">


### Excited to push the development of the extension forward! 🤗

**Comment by reklatsmasters** [comment]
Github: done, check email. VS: send me (over email) your VSID due to [issue](https://stackoverflow.com/a/56874572/1556249)

**Comment by syrusakbary** [comment]
Awesome, just sent you the email 🙂

**Comment by reklatsmasters** [comment]
Done, i sent email to MS.

**Comment by syrusakbary** [comment]
Great, thanks for moving things along.

Regarding Github, I just tried to enter the Github settings page to test adding a collaborator but I was unable to access (not sure why, perhaps is a caching issue on Github? 😱)

https://github.com/reklatsmasters/vscode-wasm/settings

<img width="1277" alt="Screen Shot 2019-09-03 at 11 56 45 AM" src="https://user-images.githubusercontent.com/188257/64200722-f0d1fb00-ce41-11e9-8a9f-fc870abde82c.png">

**Comment by reklatsmasters** [comment]
Seem like there isn’t possible to change access 
![100816A5-08E4-451D-882C-FCB15C6C3250](https://user-images.githubusercontent.com/2255752/64202684-2a8b1c00-ceab-11e9-8071-5af53ef35465.jpeg)

**Comment by syrusakbary** [comment]
Oh no! Perhaps it's because it's a personal repo and not an org one.

Would you mind maybe transferring the repo to the `wasmerio` organization? That way would be much easier for us to maintain it :)

PS: I've just added as a member of the `wasmerio` organization as well :)

**Comment by reklatsmasters** [comment]
done) Dude from MS support also approved your VS id. They also need VS id of `syrus [at] wasmer.io` to add as owner.

**Comment by syrusakbary** [comment]
Awesome, I just checked the VS marketplace and I have permissions now :)

(My Microsoft account has two emails on it - `me@syrusakbary.com` / `syrus@wasmer.io`, so no need to add another account).

Thanks for working with us on this! Closing the issue for now :)

Excited for adding new features into the extension 🚀
