### ISSUE TITLE
Can't find extension in VSCode marketplace

### ISSUE THREAD

**Issue by proehlen** [wasmerio/vscode-wasm#29]
Have tried searching for "Web Assembly", "WebAssembly" and "dtsvet.vscode-wasm" and it doesn't show up.

![image](https://user-images.githubusercontent.com/8384068/107738735-dfc93100-6d39-11eb-9bf2-089682348b59.png)

![image](https://user-images.githubusercontent.com/8384068/107738681-c1633580-6d39-11eb-9e5c-a6724feae48d.png)

![image](https://user-images.githubusercontent.com/8384068/107738782-f8394b80-6d39-11eb-9027-d908e399eb93.png)

**Comment by reklatsmasters** [comment]
Try again 

![image](https://user-images.githubusercontent.com/2255752/107950682-e3b6b680-6fb8-11eb-830d-9b6a484f6a64.png)

**Comment by proehlen** [comment]
@reklatsmasters Working now, thank you!
