### ISSUE TITLE
Add basic syntax highlighting for WAI to the WebAssembly extension

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/vscode-wasm#44]

**Comment by dynamite-bud** [comment]
Steps to implement:
 - [ ] Configure the [VSCode-WASM](https://github.com/wasmerio/vscode-wasm) as syntax highlighter for `WAI`
 - [ ] Develop a [TexMate Grammar](https://macromates.com/manual/en/language_grammars) for `WAI`

**Comment by Michael-F-Bryan** [comment]
Implemented in #51 and #46.
